fix(EP): actualizacion rutas sisa eventos
andes/sala-de-situacion pull request #134
Opened 2022-05-23 17:48 UTC by plammel

2022-05-26 12:17 UTC, martinebucarey requested changes

2022-05-26 12:17 UTC, martinebucarey commented on apps/backend/src/app/covid-events/covid-events.ts
> +        'APP_KEY': environment.snvs.appKey,
Estos dos creo que habria que agregarlos en el enviroment para que no pinche el circle algo asi:
```
snvs: {
        host: process.env.HOST_SNVS || 'prueba',
        user: process.env.USER_SNVS || 'user',
        pass: process.env.PASS_SNVS || 'unapass',
        APP_ID: process.env.appId || 'id',
        APP_KEY: process.env.appKey || 'key'
    },
```

2022-05-26 12:17 UTC, martinebucarey commented on apps/backend/src/app/covid-events/covid-events.ts
> +                    // token = await getToken(user, pass);
si el token no va mas este if estaria de mas

2022-05-31 11:29 UTC, silviroa approved these changes

2022-06-01 17:38 UTC, merged