feat(backend): Agregamos funcionalidad para envío de mails.
andes/sala-de-situacion pull request #3
Opened 2020-03-26 19:38 UTC by sychus

- Se agrega la funcionalidad para poder enviar mail. 

-  Persiste en una colección (mail) información del proceso, para ver que pasó con ese envío.

- Queda para discutir si vamos a tener una suerte de re sender para los casos de fallo.
- Se incluye test.

2020-03-26 19:43 UTC, liquid36 commented on apps/backend/src/app/services/mail/mail.routes.ts
> +MailRouter.post('/sendMail', async (req: Request, res, next) => {
Esta ruta para que la queremos? el email se manda por adentro de la api.

2020-03-26 22:45 UTC, sychus commented on apps/backend/src/app/services/mail/mail.routes.ts
> +MailRouter.post('/sendMail', async (req: Request, res, next) => {
Se quita ruta y test de la ruta porque ya no tiene sentido

2020-03-28 19:54 UTC, liquid36 requested changes

2020-03-28 19:54 UTC, liquid36 commented on apps/backend/src/environments/environment.ts
> +    host: 'smtp.gmail.com',
```suggestion
    host: process.env.MAIL_HOST ||  'smtp.gmail.com',
```

2020-03-28 19:54 UTC, liquid36 commented on apps/backend/src/environments/environment.ts
> +    port: 587,
```suggestion
    port: process.env.MAIL_PORT || 587,
```

2020-03-28 19:54 UTC, liquid36 commented on apps/backend/src/app/services/mail/mail.ts
> +        await transporter.sendMail(mailOptions, (error, info) => {
await + callback 
incompatible!

2020-03-28 19:54 UTC, liquid36 commented on apps/backend/src/app/services/mail/mail.shema.ts
> +export let Email = mongoose.model('mail', mailSchema, 'mail');
email o mail?  que quede coerente en toda la app.

2020-03-28 19:54 UTC, liquid36 commented on package.json
> +    "path": "^0.12.7",
?

2020-03-29 19:33 UTC, merged