feat(eventos): agrega campo subfiltro en indicadores
andes/sala-de-situacion pull request #34
Opened 2020-04-17 14:23 UTC by kroce

- Agrega campo subfiltro en cada indicador del evento (para permitir el filtrado por este indicador en los formularios)
- Actualiza a última versión de Plex

2020-04-17 22:32 UTC, sychus requested changes
No me funcionó! Cuando hago clic para poner el subfiltro y doy guardar no hace nada y me deja en la misma pantalla....  ¿que estoy haciendo mal?

2020-04-17 22:32 UTC, sychus commented on apps/frontend/src/app/ocurrence-events/components/ocurrence-events-list/ocurrence-events-list.component.ts
> +            console.log('indicadores ', this.indicadores);
Borrar console.log

2020-04-17 22:32 UTC, sychus commented on apps/frontend/src/app/ocurrence-events/components/ocurrence-events-list/ocurrence-events-list.component.html
> +          </plex-label> -->
Borrar

2020-04-17 22:32 UTC, sychus commented on apps/frontend/src/app/events/service/events.service.ts
> +        subfiltro: boolean;
Hay que explicar con algún plex-help que significa esto. Porque la verdad que no se entiende con ese nombre!!!

2020-04-18 12:35 UTC, kroce commented on apps/frontend/src/app/events/service/events.service.ts
> +        subfiltro: boolean;
Si, igualmente esta parte es la configuración de los eventos. Si estás ahi es porque entendés un poco el tema de los indicadores...digo

2020-04-18 13:26 UTC, condorpiedra approved these changes

2020-04-18 13:27 UTC, merged