Mejoras visuales
andes/sala-de-situacion pull request #42
Opened 2020-04-19 17:01 UTC by andrrrl

Van una serie de mejoras visuales, incluyen aspectos de:

- Layout
- Listas
- Uso de botones
- Responsiveness

Faltan incorporar más mejoras, pero estaría bueno que se mergee esta etapa así evitamos PRs interminables.

2020-04-19 20:00 UTC, sychus commented
Tengo algunos temas:
1) 
![altaEvento](https://user-images.githubusercontent.com/19353464/79698358-cad95980-825e-11ea-8cb7-97d9ffe59eb2.png)
Además de que por algún motivo se vio repetido, hay cosas que se superponen con lo que está detrás. Hay otro caso donde al menú lo tapa un input.
2) 
![instituciones](https://user-images.githubusercontent.com/19353464/79698398-0d9b3180-825f-11ea-8d18-8eba49ca50fc.png)
En intituciones, me parece medio incómoda la distribución de los campos barrio, localidad y dirección. ¿No sería mejor uno debajo del otro?
3) ![indicadores No se ve editar](https://user-images.githubusercontent.com/19353464/79698410-26a3e280-825f-11ea-950f-d6b170ba2a84.png)
El botón para editar está muuy a la izquierda dificil de ver, tal vez está muy chico. No se si los usuarios se van a dar cuenta.

2020-04-19 20:00 UTC, sychus submitted a review, later dismissed
Revisar comentarios con imágenes porfa!

2020-04-19 20:02 UTC, kroce requested changes
Mejoró mucho visualmente. Algunos detalles que encontré
- La tabla de los charts se ajustó al ancho del primer gráfico y la veo muy chica
- Subió el environment.ts con datos privados

2020-04-19 20:22 UTC, andrrrl commented
> Tengo algunos temas:
> 1)
> ![altaEvento](https://user-images.githubusercontent.com/19353464/79698358-cad95980-825e-11ea-8cb7-97d9ffe59eb2.png)
> Además de que por algún motivo se vio repetido, hay cosas que se superponen con lo que está detrás. Hay otro caso donde al menú lo tapa un input.
**No lo veo repetido, se habrá corregido en el último rebase? o decime los pasos para repetir el problema**
> 2)
> ![instituciones](https://user-images.githubusercontent.com/19353464/79698398-0d9b3180-825f-11ea-8d18-8eba49ca50fc.png)
> En intituciones, me parece medio incómoda la distribución de los campos barrio, localidad y dirección. ¿No sería mejor uno debajo del otro?
**Esa parte aun no se tocó demasiado, falta analizar e implementar**
> 3) ![indicadores No se ve editar](https://user-images.githubusercontent.com/19353464/79698410-26a3e280-825f-11ea-950f-d6b170ba2a84.png)
> El botón para editar está muuy a la izquierda dificil de ver, tal vez está muy chico. No se si los usuarios se van a dar cuenta.
**Idem anterior**

2020-04-19 20:23 UTC, andrrrl commented
> Mejoró mucho visualmente. Algunos detalles que encontré
> 
> * La tabla de los charts se ajustó al ancho del primer gráfico y la veo muy chica
> * Subió el environment.ts con datos privados

Si, me encontré con algunos estilos que no me di cuenta que estaban influyendo, ya lo limpié e hice un force-push, lo podés ver de nuevo?
También quité el env privado

2020-04-19 20:32 UTC, kroce commented
va otro detalle
![image](https://user-images.githubusercontent.com/18030170/79699118-b21f7280-8263-11ea-8130-68421655e47b.png)

2020-04-19 20:34 UTC, andrrrl commented
> va otro detalle
> ![image](https://user-images.githubusercontent.com/18030170/79699118-b21f7280-8263-11ea-8130-68421655e47b.png)

![image](https://user-images.githubusercontent.com/11394455/79699155-04609380-8264-11ea-840a-534fd17ebaed.png)
habría que ver por qué te pasa eso? hiciste npm install?

2020-04-20 13:34 UTC, condorpiedra requested changes

2020-04-20 13:34 UTC, condorpiedra commented on .gitignore
> +# env
Estos archivos se suben al repo

2020-04-20 15:30 UTC, kroce approved these changes

2020-04-20 16:01 UTC, liquid36 approved these changes

2020-04-20 16:01 UTC, merged