fix(ocurrence-events): Acceso a indicadores registrados permitidos para el usuario
andes/sala-de-situacion pull request #44
Opened 2020-04-19 22:33 UTC by silviroa

1 - Agrega control de acceso a registros de indicadores de instituciones para las cuales el usuario logueado tenga permisos.
2 - Cuando el usuario tiene acceso a solo una institución agrega el filtro por defecto

2020-04-19 23:37 UTC, sychus requested changes

2020-04-19 23:37 UTC, sychus commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
Acá faltaría verificar que tenga los permisos para acceder a los indicadores. Sino puede pasar que active su institución y aunque esta este deshabilitada va a poder meter indicadores igual. El menú solo hace que no aparezca pero si mete la url... va a poder. :-(

2020-04-19 23:58 UTC, silviroa commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
en realidad acá se están filtrando indicadores ya registrados... pero podemos agregar el control en el post

2020-04-20 00:03 UTC, liquid36 commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
La lógica que habiamos pensado era que puede registrar aunque no este activa. Cuando la validaban empezaba a contar para las estadísticas. Pero los req pueden cambiar.

2020-04-20 00:17 UTC, sychus commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
Incluso se me ocurre q al momento de activar la institución se le puede dar el permiso para meter indicadores, no?

2020-04-20 14:16 UTC, silviroa commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
Yo por ahora solo dejaría este control de acceso y después vemos los permisos mas específicos. Igualmente los usuarios que no este asociados a una institución no vas a poder cargar ningún evento nuevo

2020-04-20 16:40 UTC, kroce approved these changes

2020-04-20 18:25 UTC, sychus approved these changes

2020-04-20 18:26 UTC, sychus commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
> +                if (req.user) {
listo!!!

2020-04-20 18:26 UTC, merged