Mi perfil + AMB usuarios de Instituciones
andes/sala-de-situacion pull request #57
Opened 2020-04-27 18:13 UTC by andrrrl

Se agregó pantalla de perfil con: 

- Opción de cambio de contraseña

- Mini ABM de usuarios de Instituciones
Permite vincular usuarios con Instituciones en las que el usuario actual tiene permisos.

- Módulo de envío de preguntas y sugerencias
Formulario para envío de preguntas, sugerencias o reporte de problemas, envío de email con formato.

2020-04-29 12:21 UTC, sychus requested changes
revisar estas cosillas

2020-04-29 12:21 UTC, sychus commented on apps/backend/src/app/services/mail/mail.ts
> +  return new Promise((resolve, reject) => {
no va mas new Promise. Usar async await

2020-04-29 12:21 UTC, sychus commented on apps/backend/src/app/templates/email/suggestions.html
> +                            style="padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff">
style inline?

2020-04-29 12:21 UTC, sychus commented on apps/backend/src/app/templates/email/suggestions.html
> +    </style>
sacar afuera esto

2020-04-29 12:21 UTC, sychus commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +            }
???

2020-04-29 12:21 UTC, sychus commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +        console.log(institution.users);
quitar console.log

2020-04-29 12:21 UTC, sychus commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +        console.log(this.selectedUser.id);
quitar console.log

2020-04-29 12:27 UTC, andrrrl commented on apps/backend/src/app/templates/email/suggestions.html
> +                            style="padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff">
Si, es HTML de un email, si no algunos clientes de email te lo limpian, te desactivan cosas... confiá en mí :smile_cat:

2020-04-29 13:32 UTC, andrrrl commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +            }
Se agrega un plex.info para ese caso

2020-04-29 15:33 UTC, kroce submitted a review, later dismissed
Me da un error cuando quiero reestablecer la contraseña. Me llega el mail, coloco dos veces la clave y cuando voy a confirmar me da un error (sale un toast).
También me pasa que agrego un usuario a la institución y no me lo guarda

2020-05-02 14:19 UTC, kroce submitted a review, later dismissed
- Probando con mi usuario, el mail de sugerencias me llega a mi misma
- Me parece mas claro dejar la opción de "Mi Perfil" solo para los usuarios de la institución (no para el usuario administrador)

2020-05-04 12:45 UTC, juuliotero commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +        console.log(this.selectedUser.id);
Listo

2020-05-04 12:45 UTC, juuliotero commented on apps/frontend/src/app/login/components/perfil/user-profile.component.ts
> +        console.log(institution.users);
Listo

2020-05-04 19:53 UTC, sychus requested changes

2020-05-04 19:53 UTC, sychus commented on apps/backend/src/app/services/mail/mail.ts
> +        to: 'andresin@gmail.com',
todos los mails para vos? andresin?

2020-05-04 19:55 UTC, sychus commented on apps/backend/src/app/services/mail/mail.ts
> +        to: 'andresin@gmail.com',
![image](https://user-images.githubusercontent.com/19353464/81007644-fe53e080-8e27-11ea-94ad-484218eb5d23.png)
No debería estar el "Volver" en la página de login

2020-05-04 19:56 UTC, sychus commented on apps/backend/src/app/services/mail/mail.ts
> +        to: 'andresin@gmail.com',
![image](https://user-images.githubusercontent.com/19353464/81007759-30fdd900-8e28-11ea-9296-604150f4c220.png)
Y la pantalla de perfil??? no está más?

2020-05-05 03:11 UTC, sychus requested changes
Importante resolver este bug!

2020-05-05 03:11 UTC, sychus commented on apps/backend/src/app/auth/auth.routes.ts
> +AuthRouter.post('/auth/updatePassword', async (req: Request, res, next) => {
Horror!!! Este post tiene que ir application.authenticate. Le acabo de hackear la clave a la cuenta andresin!

2020-05-05 11:07 UTC, andrrrl commented on apps/backend/src/app/services/mail/mail.ts
> +        to: 'andresin@gmail.com',
- Resuelto lo del email :man_facepalming: 
- El botón volver está desde el principio, se charló de quitarlo pero no corresponde en esta rama.

2020-05-05 12:46 UTC, sychus approved these changes
Great!!

2020-05-05 13:14 UTC, kroce approved these changes

2020-05-05 13:15 UTC, merged