EVENTOS: no permitir modificar el key a los eventos que tengan indicadores
andes/sala-de-situacion pull request #62
Opened 2020-04-30 13:51 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/SAL-55

### Funcionalidad desarrollada 
1. Si el mismo tiene asociado indicadores, deberá deshabilitarse la edición de la key. Caso contrario se podrá cambiar.

2020-04-30 18:31 UTC, sychus approved these changes
ok, hay que ver el tema de lint. Porque hay un montón de archivos que no fueron modificados.

2020-04-30 19:40 UTC, juuliotero commented
> ok, hay que ver el tema de lint. Porque hay un montón de archivos que no fueron modificados.

Corregido el linteo.

2020-05-02 13:29 UTC, sychus approved these changes

2020-05-04 11:26 UTC, kroce submitted a review, later dismissed
Cuando doy de alta un nuevo evento me indica que la clave es requerida aunque tenga un valor
![image](https://user-images.githubusercontent.com/18030170/80961222-dd1bd180-8de0-11ea-9485-de8fc2f09e81.png)

2020-05-04 12:36 UTC, juuliotero commented
> Cuando doy de alta un nuevo evento me indica que la clave es requerida aunque tenga un valor
> ![image](https://user-images.githubusercontent.com/18030170/80961222-dd1bd180-8de0-11ea-9485-de8fc2f09e81.png)

Solucionado!

2020-05-05 13:42 UTC, kroce requested changes
Ahora tengo el siguiente error: creo un nuevo evento, no le cargo ningún indicador y cuando quiero modificarle la clave ya no puedo

2020-05-06 18:01 UTC, sychus commented
> Ahora tengo el siguiente error: creo un nuevo evento, no le cargo ningún indicador y cuando quiero modificarle la clave ya no puedo

Esto ya quedo? @juuliotero ??

2020-05-06 18:30 UTC, juuliotero commented
> > Ahora tengo el siguiente error: creo un nuevo evento, no le cargo ningún indicador y cuando quiero modificarle la clave ya no puedo
> 
> Esto ya quedo? @juuliotero ??

Si! Recién lo subí. Entendí la us como control de indicadores, no de las ocurrencias.

2020-05-07 15:10 UTC, kroce approved these changes

2020-05-07 15:10 UTC, merged