OCURRENCE-EVENTS: fecha por default y control de fecha mínima
andes/sala-de-situacion pull request #63
Opened 2020-04-30 17:19 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/SAL-49

### Funcionalidad desarrollada 
1. Al registrar un indicador, cargar por default la fecha y hora actual
2. Controlar que no se cargue una fecha fecha anterior a la del último registro cargado
3. Carga por defecto del combo de eventos en el onInit()

2020-04-30 18:53 UTC, sychus approved these changes
Ok, ojo con lo que no se usa y el linteo

2020-04-30 18:53 UTC, sychus commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
>  import * as mongoose from 'mongoose';
Borrar

2020-04-30 19:37 UTC, juuliotero commented on apps/backend/src/app/ocurrence-events/ocurrence-events.controller.ts
>  import * as mongoose from 'mongoose';
Se borró el import. Acomodé el linteo, se rompe porque el .editorconfig tiene indent_size = 2, y pise el settings.

2020-05-05 14:11 UTC, kroce requested changes
@juuliotero no me odies, fui a cargar un nuevo registro de un evento nuevo y plum
![image](https://user-images.githubusercontent.com/18030170/81075763-26435280-8ec1-11ea-9057-cee457761870.png)

2020-05-06 18:01 UTC, sychus commented
> @juuliotero no me odies, fui a cargar un nuevo registro de un evento nuevo y plum
> ![image](https://user-images.githubusercontent.com/18030170/81075763-26435280-8ec1-11ea-9057-cee457761870.png)

2020-05-07 14:15 UTC, kroce approved these changes

2020-05-07 14:15 UTC, merged