feat(login): agrega el módulo de auth
andes/sala-de-situacion pull request #7
Opened 2020-03-30 10:38 UTC by condorpiedra

Funcionalidad desarrollada:

- Agrega un módulo login para realizar la autenticación 
- Registro de nuevo usuario
- Agrega routing para la activación de la cuenta.

2020-03-30 12:58 UTC, sychus approved these changes
**Me anduvo re bien!!** Sólo un detalle al compilar se ve que hay algún tema con angular y versiones nuevas de typescript. 
ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 (en mi caso tenía una versión más nueva de typescript).
Tal vez convenga en el package.json en vez de tener:
"typescript": "^3.4.5" sería conveniente tener: "typescript": "~3.4.5" ?

2020-03-30 12:58 UTC, sychus commented on apps/backend/src/main.ts
> +//const MailRouter = require('./app/services/mail/mail.routes').MailRouter;
```suggestion
//const MailRouter = require('./app/services/mail/mail.routes').MailRouter;
```
Borrar ya que me habían quedado mal a mi del PR anterior

2020-03-31 05:50 UTC, sychus commented
@condorpiedra fijate que te parece esta modificación en el flujo, ya que me parece que refleja un poquito mejor lo que charlamos y simplifica un poco el proceso.

2020-03-31 12:30 UTC, kroce approved these changes

2020-03-31 14:18 UTC, liquid36 requested changes

2020-03-31 14:18 UTC, liquid36 commented on apps/backend/src/app/services/mail/mail.ts
> +    const url = `http://localhost:4200/login/activacion-cuenta/${validationToken}`;
parametrizaría el host.
```suggestion
    const url = `${env.APP_HOST}/login/activacion-cuenta/${validationToken}`;
```

2020-03-31 14:18 UTC, liquid36 commented on apps/backend/src/app/services/mail/mail.ts
> +        text: `${nombre} , gracias por registrar tu cuenta. Para activarla copia y pega la siguiente dirección: ${url}`,
¿Copia y pega la siguiente dirección? Haz click aquí!

```
haz <a href="${url}"> click aquí. </a>
```

2020-03-31 14:23 UTC, liquid36 commented on apps/frontend/src/app/app.module.ts
> +  declarations: [AppComponent, AppHomeComponent],
Ojo con esos linteos!

2020-03-31 14:24 UTC, liquid36 commented on apps/frontend/src/app/app.module.ts
> +  declarations: [AppComponent, AppHomeComponent],
Meter cambios en paralelo en una misma linea de código siempre es un lio

2020-03-31 15:24 UTC, condorpiedra commented on apps/backend/src/main.ts
> +//const MailRouter = require('./app/services/mail/mail.routes').MailRouter;
Se eliminan los comentarios.  Se setea la versión de Typescript según sugerencia

2020-03-31 15:25 UTC, condorpiedra commented on apps/backend/src/app/services/mail/mail.ts
> +    const url = `http://localhost:4200/login/activacion-cuenta/${validationToken}`;
se realiza sugerencia con los datos de environment

2020-03-31 15:25 UTC, condorpiedra commented on apps/backend/src/app/services/mail/mail.ts
> +        text: `${nombre} , gracias por registrar tu cuenta. Para activarla copia y pega la siguiente dirección: ${url}`,
En realidad faltaría realizar el html y consensuar el mensaje a enviar

2020-03-31 15:27 UTC, condorpiedra commented on apps/frontend/src/app/app.module.ts
> +  declarations: [AppComponent, AppHomeComponent],
Se realizó la  verificación del linteo del archivo, y se realizó la actualización del archivo

2020-03-31 17:19 UTC, sychus approved these changes

2020-03-31 18:08 UTC, merged