EVENTS: al cargar indicadores trae los recursos de la base
andes/sala-de-situacion pull request #86
Opened 2020-06-16 18:29 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/SAL-51

### Funcionalidad desarrollada 
1. Nuevo schema y controller para Resources
2. Carga de recursos en events-crud desde la base

2020-06-17 13:29 UTC, kroce requested changes
Creé en test un evento nuevo "prueba" que tiene un campo select de localidad y cuando quise cargar un indicador me da un error. Adjunto captura
![image](https://user-images.githubusercontent.com/18030170/84904177-659abc80-b085-11ea-921a-40ff8e6ea082.png)

2020-06-18 15:11 UTC, juuliotero commented
> Creé en test un evento nuevo "prueba" que tiene un campo select de localidad y cuando quise cargar un indicador me da un error. Adjunto captura
> ![image](https://user-images.githubusercontent.com/18030170/84904177-659abc80-b085-11ea-921a-40ff8e6ea082.png)

Había un problema con los nombres de los recursos, las rutas a provincia y localidad son singulares, por lo tanto el key de los recursos tienen que ser en singular.

2020-06-22 04:53 UTC, sychus approved these changes
El código se ve correcto!

2020-06-24 13:25 UTC, sychus commented
@kroce lo podrías volver a probar porfa?

2020-06-24 15:37 UTC, condorpiedra commented
No se precargan los recursos en la configuración de eventos
![image](https://user-images.githubusercontent.com/19696043/85586628-757f4700-b617-11ea-92b9-78bc0ae84231.png)

2020-06-24 17:49 UTC, juuliotero commented
> No se precargan los recursos en la configuración de eventos
> ![image](https://user-images.githubusercontent.com/19696043/85586628-757f4700-b617-11ea-92b9-78bc0ae84231.png)

Hay que cargar en resources estos objetos: https://gist.github.com/juuliotero/e54e16de43735a0d4b59069437433b4c

2020-06-24 17:57 UTC, condorpiedra commented
> > No se precargan los recursos en la configuración de eventos
> > ![image](https://user-images.githubusercontent.com/19696043/85586628-757f4700-b617-11ea-92b9-78bc0ae84231.png)
> 
> Hay que cargar en resources estos objetos, habían quedado en la base de test: https://gist.github.com/juuliotero/e54e16de43735a0d4b59069437433b4c

Están cargados

2020-06-24 18:07 UTC, kroce approved these changes

2020-06-24 19:02 UTC, merged